-- =====================================================================
-- EvalHub (Assessment Helper) — Sprint 1 / Week 1 schema
-- Target: PostgreSQL 14+
--
-- Scope: the core data layer only — users, teachers, terms, courses and
-- course sections. Assessment / observation tables arrive with Sprint 2
-- as a new numbered migration (002_...). Never edit an applied migration.
--
-- Conventions
--   * snake_case; TEXT + CHECK for role/rank (easy to extend later)
--   * IDENTITY "BY DEFAULT" so seed/import scripts may supply explicit ids
--   * the migration runner wraps each file in a transaction — no BEGIN/COMMIT here
-- =====================================================================

CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Academic terms. Needed now so course sections (teaching history) can be dated.
CREATE TABLE terms (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season       TEXT     NOT NULL CHECK (season IN ('spring', 'summer', 'fall')),
  year         SMALLINT NOT NULL CHECK (year BETWEEN 2000 AND 2100),
  start_date   DATE     NOT NULL,
  end_date     DATE     NOT NULL,
  is_long_term BOOLEAN GENERATED ALWAYS AS (season <> 'summer') STORED,
  UNIQUE (year, season),
  CHECK (end_date > start_date)
);

CREATE TABLE teachers (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  email      TEXT NOT NULL,
  -- Home school as a short upper-case code: 'ECS', 'EPPS', ... ("observer must be from the same school")
  school     TEXT NOT NULL,
  rank       TEXT NOT NULL CHECK (rank IN ('assistant_professor', 'associate_professor', 'full_professor')),
  is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX teachers_email_uq ON teachers (lower(email));
CREATE INDEX teachers_school_idx ON teachers (school) WHERE is_active;

-- Login accounts.
--   faculty    -> a teacher
--   ac_member  -> Assessment Committee (also a teacher; can step in as observer later)
--   admin      -> system administration (no teacher record required)
CREATE TABLE users (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'faculty' CHECK (role IN ('faculty', 'ac_member', 'admin')),
  teacher_id    INT UNIQUE REFERENCES teachers (id) ON DELETE SET NULL,
  is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_uq ON users (lower(email));

CREATE TABLE courses (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject       TEXT NOT NULL,                                     -- 'CS'
  -- School that owns the course ('ECS', 'EPPS', ...). Observer eligibility is by
  -- (school, level): an ECS 1000-level instructor may observe any ECS 1000-level
  -- course, but an EPPS 1000-level instructor may not (Q&A, question 8).
  school        TEXT NOT NULL,
  course_number TEXT NOT NULL CHECK (course_number ~ '^[0-9]{4}$'), -- '4485'
  title         TEXT NOT NULL,
  -- Course level = most significant digit of the course number (CS 4485 -> 4).
  -- Derived by the database so it can never disagree with the number.
  course_level  SMALLINT GENERATED ALWAYS AS (left(course_number, 1)::smallint) STORED,
  source        TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'coursebook', 'seed')),
  external_id   TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (subject, course_number)
);
CREATE INDEX courses_school_level_idx ON courses (school, course_level);

-- One row per course offering. teacher_id + term_id is the "historical
-- instructors" data; the UTD Course Book integration will write here.
CREATE TABLE course_sections (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id      INT  NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  term_id        INT  NOT NULL REFERENCES terms (id)   ON DELETE RESTRICT,
  section_number TEXT NOT NULL,                                    -- '001', '0U1'
  teacher_id     INT  REFERENCES teachers (id) ON DELETE SET NULL, -- NULL = TBA
  meeting_days   TEXT,                                             -- 'MW', 'TR'
  start_time     TIME,
  end_time       TIME,
  location       TEXT,
  source         TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'coursebook', 'seed')),
  external_id    TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_id, term_id, section_number)
);
CREATE INDEX course_sections_teacher_term_idx ON course_sections (teacher_id, term_id);
CREATE INDEX course_sections_term_idx ON course_sections (term_id);

-- updated_at triggers
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['teachers', 'users', 'courses', 'course_sections'] LOOP
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      t || '_set_updated_at', t
    );
  END LOOP;
END;
$$;
