-- =====================================================================
-- EvalHub — Sprint 2 / assessment workflow schema
-- Adds: assessments, candidate_lists, observer_candidates, observations,
--       evaluation_criteria, process_feedback, app_settings.
--
-- Requirement source: 9/11 Q&A + meeting summary (not the original sprint
-- plan wording, which is superseded where the two disagree — see
-- docs/schema.md §"Sprint plan vs. requirements").
--
-- Key correction from the original plan: an assessment is NOT one row per
-- teacher per term. Q&A 18 says "For one course/section, there will be
-- only 1 observation. The Professor can sign up to be observed for
-- different courses" — so a teacher may have several assessments in the
-- same term (one per section they sign up with), and a section can be
-- claimed by exactly one assessment (UNIQUE below).
--
-- Ownership (per Sprint 2 split): this migration + the sign-up API belong
-- to Backend/Data (Prethel). The matching algorithm and AC-approval
-- endpoints that write into candidate_lists / observations belong to
-- Fabian — the tables are ready for him to build against.
-- =====================================================================

-- Tunable rules the AC/admin may need to change without a deploy.
CREATE TABLE app_settings (
  key         TEXT PRIMARY KEY,
  value       JSONB       NOT NULL,
  description TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO app_settings (key, value, description) VALUES
  ('candidate_list_size',     '5',                    'Exactly this many observer candidates are surfaced per request (Q&A 15)'),
  ('observer_lookback_years', '2',                    'Observer must have taught the target level, in the same school, within this many years (Q&A 8)'),
  ('retry_window_weeks',      '{"min": 3, "max": 4}', 'If an observation does not happen, retry within this window, then AC / postponement (9/11 summary)');

-- One row per (teacher, section) sign-up. A teacher may sign up for several
-- sections in a term; a section can be claimed by only one assessment.
CREATE TABLE assessments (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id   INT  NOT NULL REFERENCES teachers (id) ON DELETE RESTRICT,       -- the observee
  section_id   INT  NOT NULL REFERENCES course_sections (id) ON DELETE RESTRICT,
  due_term_id  INT  NOT NULL REFERENCES terms (id) ON DELETE RESTRICT,          -- term this counts toward (= section's term)
  status       TEXT NOT NULL DEFAULT 'signed_up' CHECK (status IN (
                 'signed_up',            -- teacher submitted the sign-up form
                 'candidates_generated', -- ~5 candidates surfaced (Fabian's endpoint)
                 'pending_ac_approval',  -- teacher's chosen observer sent to AC
                 'approved',             -- AC approved; communication may go out
                 'completed',            -- observation done + both sign-offs
                 'not_eligible',         -- AC determined the teacher was not actually due (Eligibility Accuracy KPI)
                 'postponed',
                 'cancelled')),
  signed_up_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (section_id),      -- "for one course/section there will be only 1 observation" (Q&A 18)
  UNIQUE (id, teacher_id)   -- lets observations' composite FK below guarantee observee consistency
);
CREATE INDEX assessments_teacher_idx ON assessments (teacher_id);
CREATE INDEX assessments_status_idx ON assessments (due_term_id, status);

-- Snapshot each time candidates are surfaced. pool_size (eligible found) vs
-- list_size (returned, capped at app_settings.candidate_list_size) drives
-- the List Sufficiency and Unmatched Faculty KPIs.
CREATE TABLE candidate_lists (
  id            INT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id INT      NOT NULL REFERENCES assessments (id) ON DELETE CASCADE,
  target_level  SMALLINT NOT NULL,  -- course_level of the assessment's section, captured at generation time
  target_school TEXT     NOT NULL,  -- school the observer must match, captured at generation time
  pool_size     INT      NOT NULL CHECK (pool_size >= 0),
  list_size     INT      NOT NULL CHECK (list_size >= 0),
  generated_by  INT REFERENCES users (id) ON DELETE SET NULL,
  generated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (list_size <= pool_size)
);
CREATE INDEX candidate_lists_assessment_idx ON candidate_lists (assessment_id);

CREATE TABLE observer_candidates (
  list_id    INT      NOT NULL REFERENCES candidate_lists (id) ON DELETE CASCADE,
  teacher_id INT      NOT NULL REFERENCES teachers (id) ON DELETE RESTRICT,
  position   SMALLINT NOT NULL CHECK (position > 0),
  PRIMARY KEY (list_id, teacher_id),
  UNIQUE (list_id, position)
);
CREATE INDEX observer_candidates_teacher_idx ON observer_candidates (teacher_id);

-- The observer/observee record. Human-in-the-loop is enforced by the
-- database, not just the API: a record cannot be approved/completed
-- without an AC review timestamp, and cannot be completed without both
-- sign-offs (9/11 summary, "workflow" section).
CREATE TABLE observations (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id          INT NOT NULL,
  observee_id            INT NOT NULL,  -- denormalised on purpose: the composite FK below guarantees it matches assessments.teacher_id
  observer_id            INT NOT NULL REFERENCES teachers (id) ON DELETE RESTRICT,
  attempt_no             SMALLINT NOT NULL DEFAULT 1 CHECK (attempt_no > 0),  -- retries (illness, conflicts, etc.) are new attempts, not overwrites
  source_list_id         INT REFERENCES candidate_lists (id) ON DELETE SET NULL,  -- NULL when AC stepped in directly (new-hire edge case)
  is_ac_stepin           BOOLEAN NOT NULL DEFAULT FALSE,
  status                 TEXT NOT NULL DEFAULT 'proposed' CHECK (status IN (
                           'proposed',       -- requesting professor contacted this observer; awaiting AC
                           'approved',       -- AC approved; communication may go out
                           'rejected',       -- AC rejected; back to candidates
                           'completed',      -- observed + both signed off
                           'not_completed',  -- did not happen (illness, conflict, etc.)
                           'postponed')),
  ac_reviewed_by         INT REFERENCES users (id) ON DELETE SET NULL,
  ac_reviewed_at         TIMESTAMPTZ,
  ac_notes               TEXT,
  scheduled_date         DATE,
  observer_signed_off_at TIMESTAMPTZ,
  observee_signed_off_at TIMESTAMPTZ,
  retry_after            DATE,   -- 3-4 week retry window (9/11 summary)
  form_file_ref          TEXT,   -- pointer to the filled DOCX observation form; contents not parsed/analysed
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (assessment_id, observee_id) REFERENCES assessments (id, teacher_id) ON DELETE CASCADE,
  CHECK (observer_id <> observee_id),
  UNIQUE (assessment_id, attempt_no),
  CHECK (status NOT IN ('approved', 'completed', 'not_completed') OR ac_reviewed_at IS NOT NULL),
  CHECK (status <> 'completed' OR (observer_signed_off_at IS NOT NULL AND observee_signed_off_at IS NOT NULL))
);
CREATE INDEX observations_observer_idx ON observations (observer_id);
CREATE INDEX observations_status_idx ON observations (status);

-- AC-configurable criteria, weights and scoring (9/11 summary: clarity,
-- engagement, preparedness, rigor, pace, organization, technology use, etc.)
CREATE TABLE evaluation_criteria (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT,
  weight      NUMERIC(5, 2) NOT NULL DEFAULT 1 CHECK (weight >= 0),
  max_score   SMALLINT      NOT NULL DEFAULT 5 CHECK (max_score > 0),
  sort_order  SMALLINT      NOT NULL DEFAULT 0,
  is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
  updated_by  INT REFERENCES users (id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Process feedback web form (up to one response per participant per observation).
CREATE TABLE process_feedback (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id INT NOT NULL REFERENCES observations (id) ON DELETE CASCADE,
  respondent_id  INT NOT NULL REFERENCES teachers (id) ON DELETE RESTRICT,
  rating         SMALLINT CHECK (rating BETWEEN 1 AND 5),
  comments       TEXT,
  submitted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (observation_id, respondent_id)
);

-- updated_at triggers (set_updated_at() already exists from migration 001)
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['assessments', 'observations', 'evaluation_criteria'] LOOP
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      t || '_set_updated_at', t
    );
  END LOOP;
END;
$$;
