-- Multi-date scheduling (#8-10, requirements.md §4.3 step 4).
--
-- NUMBERING: this is 004 because Fabian already used 003
-- (003_remove_ac_approval.sql, ticket #19). Before applying this,
-- run `ls db/migrations/` on a freshly-pulled main and confirm 004
-- is genuinely the next free number -- rename this file first if not.
--
-- Workflow this supports (requirements.md §4.3 step 4, current/final version):
--   1. Observee picks ONE observer from the candidate list.
--   2. Observee offers 4-8 possible observation dates/times for that
--      pairing. Course-schedule conflicts are checked elsewhere (the
--      matching query); personal/Outlook calendars are not -- that's
--      exactly why multiple options are offered, so the observer can
--      pick one that works for them.
--   3. A single request goes out to that one observer (not multiple
--      observers at once -- the 9/18 "send to several, first-to-accept
--      wins" model was superseded on 9/30).
--   4. The observer confirms exactly one date. That becomes the
--      scheduled/confirmed pairing (still not "Completed" -- that
--      status only applies once the observation itself happened AND
--      both parties signed off; see observations.status).
--
-- This table only needs assessments(id) to exist, so it's safe to
-- apply regardless of whatever changed in observations.js / migration
-- 003 for #19 -- no dependency on that table's current shape.

CREATE TABLE assessment_time_options (
  id                    INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id         INT  NOT NULL REFERENCES assessments (id) ON DELETE CASCADE,
  proposed_date         DATE NOT NULL,
  start_time            TIME NOT NULL,
  end_time              TIME NOT NULL,
  -- Set when the observee sends the request to their one chosen observer.
  -- NULL until then; the API updates every option row for this assessment
  -- together, in one statement, so they all point at the same observer.
  offered_to_teacher_id INT  REFERENCES teachers (id) ON DELETE SET NULL,
  is_confirmed          BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (end_time > start_time),
  UNIQUE (assessment_id, proposed_date, start_time)
);

CREATE INDEX assessment_time_options_assessment_idx ON assessment_time_options (assessment_id);

-- At most one confirmed date per assessment. A partial unique index
-- (not a CHECK) because the rule only applies to rows where
-- is_confirmed is true -- Postgres can't express "at most one true
-- across a group of rows" as a plain CHECK constraint.
CREATE UNIQUE INDEX assessment_time_options_one_confirmed_idx
  ON assessment_time_options (assessment_id) WHERE is_confirmed;

-- The "4-8 options" rule itself is enforced in the API layer, not here.
-- A CHECK constraint can't count sibling rows, and a trigger for this
-- is more complexity than it's worth for a count range -- the API
-- validates the batch size on insert instead.
